In [1]:
import pandas as pd
import numpy as np


#1# Basic Data Exploration 

# Load dataset into a pandas dataframe

Sales_data = pd.read_csv(r'C:\Users\dell\OneDrive\Desktop\AI\Practice file by sir\sales.csv')

customer_data = pd.read_csv(r'C:\Users\dell\OneDrive\Desktop\AI\Practice file by sir\customers.csv')

Sdata_fram =pd.DataFrame(Sales_data)

Cdata_fram =pd.DataFrame(customer_data)

display('Sales Dataset:',Sdata_fram)

display('Customers Dataset:',Cdata_fram)

'Sales Dataset:'

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

'Customers Dataset:'

     order_id  customer_rating
0           1                1
1           2                1
2           3                2
3           4                1
4           5                4
..        ...              ...
495       496                3
496       497                4
497       498                4
498       499                1
499       500                1

[500 rows x 2 columns]

In [2]:
Shead_row = Sdata_fram.head(8)

display('Sales frist 8 rows',Shead_row)

Chead_row = Cdata_fram.head(8)


display('Customers frist 8 rows',Chead_row)

'Sales frist 8 rows'

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

'Customers frist 8 rows'

   order_id  customer_rating
0         1                1
1         2                1
2         3                2
3         4                1
4         5                4
5         6                2
6         7                1
7         8                2

In [3]:
display('Sales data information:',Sales_data.info())

display('Customers data information:',customer_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    object
 2   region         500 non-null    object
 3   product        500 non-null    object
 4   category       500 non-null    object
 5   customer_type  500 non-null    object
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), object(5)
memory usage: 39.2+ KB

'Sales data information:'

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   customer_rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB

'Customers data information:'

None

In [4]:
display('Sales Statistical data:',Sales_data.describe())

display('Customers Statistical data: ',customer_data.describe())

'Sales Statistical data:'

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

'Customers Statistical data: '

         order_id  customer_rating
count  500.000000       500.000000
mean   250.500000         2.480000
std    144.481833         1.118975
min      1.000000         1.000000
25%    125.750000         1.000000
50%    250.500000         2.500000
75%    375.250000         3.000000
max    500.000000         4.000000

In [5]:
display('Sales Columns names:',Sales_data.columns)

display('Customers Columns names: ',customer_data.columns)

'Sales Columns names:'

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='object')

'Customers Columns names: '

Index(['order_id', 'customer_rating'], dtype='object')

In [6]:
# # Multiple replacements
# df['Department'] = df['Department'].replace({
#     'HR': 'Human Resources',
#     'Finance': 'Financial Services'
# })


Sreplace_id =Sales_data['order_id'].rename('OrderID', inplace=True)

display(Sreplace_id)


Creplace_id =customer_data['order_id'].rename('OrderID', inplace=True)

display(Creplace_id)

0        1
1        2
2        3
3        4
4        5
      ...
495    496
496    497
497    498
498    499
499    500
Name: OrderID, Length: 500, dtype: int64

0        1
1        2
2        3
3        4
4        5
      ...
495    496
496    497
497    498
498    499
499    500
Name: OrderID, Length: 500, dtype: int64

In [7]:
display(Sales_data.columns)

display(customer_data.columns)

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='object')

Index(['order_id', 'customer_rating'], dtype='object')

In [8]:
Smissing_values = Sales_data.isnull().sum()
display(Smissing_values)


Cmissing_values = customer_data.isnull().sum()
display(Cmissing_values)

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

order_id           0
customer_rating    0
dtype: int64

In [9]:
Sduplicate_rows = Sales_data.duplicated().sum()
display('Sales duplicate rows',Sduplicate_rows)

Cduplicate_rows = customer_data.duplicated().sum()
display('Customer duplicate rows',Cduplicate_rows)

'Sales duplicate rows'

np.int64(0)

'Customer duplicate rows'

np.int64(0)

In [10]:
Sdate_change = Sales_data['date']= pd.to_datetime(Sales_data['date'])

display(Sdate_change)

0     2024-04-12
1     2024-12-14
2     2024-09-27
3     2024-04-16
4     2024-03-12
         ...
495   2024-11-20
496   2024-01-04
497   2024-01-16
498   2024-10-06
499   2024-12-01
Name: date, Length: 500, dtype: datetime64[ns]

In [11]:
S_dtype = Sales_data.dtypes
display(S_dtype)

order_id                  int64
date             datetime64[ns]
region                   object
product                  object
category                 object
customer_type            object
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [12]:
ptype_change =Sales_data['price']= Sales_data['price'].astype(float)

display(Sales_data['price'])

0       590.0
1       262.0
2       512.0
3       485.0
4       332.0
        ...
495     314.0
496     369.0
497     722.0
498    1449.0
499     869.0
Name: price, Length: 500, dtype: float64

In [13]:
region_names = Sales_data['region'].value_counts()

display(region_names)

region
North    151
East     118
South    116
West     115
Name: count, dtype: int64

In [14]:
total_sales = Sales_data.groupby('region')['sales'].sum()

display(total_sales)

display(total_sales.max())
#df_merged.groupby('product')['sales'].sum()

region
East     422023.71
North    509052.69
South    362158.72
West     373294.66
Name: sales, dtype: float64

np.float64(509052.69)

In [15]:
avg_discount = Sales_data.groupby('product')['discount'].mean()

display(avg_discount)

product
Keyboard    0.147436
Laptop      0.141149
Monitor     0.147733
Mouse       0.153021
Phone       0.155125
Tablet      0.135357
Name: discount, dtype: float64

In [16]:
customer_rating = customer_data['customer_rating']
display(customer_rating)

0      1
1      1
2      2
3      1
4      4
      ..
495    3
496    4
497    4
498    1
499    1
Name: customer_rating, Length: 500, dtype: int64

In [35]:
cs_merged = pd.merge(Sales_data, customer_data, on='order_id')

display(avg_discount)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales,customer_rating
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4295.20,1
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,429.68,1
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2329.60,2
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,441.35,1
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,1812.72,4
...,...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1450.68,3
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,2557.17,4
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,3725.52,4
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2550.24,1
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1581.58,1

In [37]:
avg_rating = cs_merged.groupby('customer_type')['customer_rating'].mean()

display(avg_rating)

customer_type
New          2.472803
Returning    2.486590
Name: customer_rating, dtype: float64

In [41]:
## 5 top products 

top_products = cs_merged.groupby('product')['quantity'].max()

display(top_products)

product
Keyboard    9
Laptop      9
Monitor     9
Mouse       9
Phone       9
Tablet      9
Name: quantity, dtype: int64