Pandas DataFrame Detective
Objective: 
Perform basic exploratory data analysis using Pandas. 
Instructions:
1. Import pandas as pd and numpy as np. 
2. Create dictionary: data = {'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],'Age': [25,30,np.nan,35,28,np.nan],'Score': [85,92,78,np.nan,88,95],'Grade': ['A','A','B','C','B','A']} 
3. Create DataFrame df. 
4. Perform:   - df.head(3)   - df.shape   - df.columns   - df.dtypes 
5. Missing data:   - df.isnull()   - Fill Age with mean   - Drop rows with missing Score 
6. Selection:   - Select Name and Score   - Select rows where Score > 85   - Set Name as index 
7. Operations:   - Unique grades   - Grade counts   - Sort by Score descending

In [4]:
#1. Import pandas as pd and numpy as np. 

import pandas as pd
import numpy as np

In [ ]:
#2. Create dictionary:


data = {
        'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
        'Age': [25,30,np.nan,35,28,np.nan],
        'Score': [85,92,78,np.nan,88,95],
        'Grade': ['A','A','B','C','B','A']
        }

In [ ]:
#3. Create DataFrame df.

df = pd.DataFrame(data)
data

{'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
 'Age': [25, 30, nan, 35, 28, nan],
 'Score': [85, 92, 78, nan, 88, 95],
 'Grade': ['A', 'A', 'B', 'C', 'B', 'A']}

In [ ]:
#4. Perform:   - df.head(3)   - df.shape   - df.columns   - df.dtypes

print('First three rows:', df.head(3))

First three rows:       Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B

In [9]:
df.shape

(6, 4)

In [10]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')

In [11]:
df.dtypes

Name      object
Age      float64
Score    float64
Grade     object
dtype: object

In [13]:
#5. Missing data:   - df.isnull()   - Fill Age with mean   - Drop rows with missing Score 


df.isnull().sum()

Name     0
Age      2
Score    1
Grade    0
dtype: int64

In [17]:
mean_value =df['Age'].mean()

df['Age'].fillna(mean_value, inplace=True)

In [26]:
df.dropna(subset=['Score'])

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

In [30]:
#6. Selection:   - Select Name and Score   - Select rows where Score > 85   - Set Name as index 


select_result = df[['Name', 'Score']][df['Score']>85].set_index('Name')

select_result

       Score
Name
Bob     92.0
Eve     88.0
Frank   95.0

In [31]:
#7. Operations:   - Unique grades   - Grade counts   - Sort by Score descending
df['Grade'].unique()

array(['A', 'B', 'C'], dtype=object)

In [32]:
df['Grade'].value_counts()

Grade
A    3
B    2
C    1
Name: count, dtype: int64

In [33]:
df['Score'].sort_values(ascending=False)

5    95.0
1    92.0
4    88.0
0    85.0
2    78.0
3     NaN
Name: Score, dtype: float64