               Week 3 – NumPy and Pandas Assignments & Quizzes

<!-- 1. Import NumPy as np.
2. Create the following arrays:
   - Array A: 1D array from list [2,4,6,8,10,12,14,16,18,20]
   - Array B: 3x3 array of zeros
   - Array C: 5 random integers between 1 and 100
   - Array D: 10 evenly spaced numbers between 0 and 5 using np.linspace() -->

In [176]:
import numpy as np

In [177]:
#- Array A: 1D array from list [2,4,6,8,10,12,14,16,18,20]

list = [2,4,6,8,10,12,14,16,18,20]

Array_A = np.array(list)

print(Array_A)

[ 2  4  6  8 10 12 14 16 18 20]

In [178]:
#- Array B: 3x3 array of zeros

Array_B = np.array([[0,0,0],[0,0,0],[0,0,0]])

print('3 * 3 array:\n',Array_B)

3 * 3 array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

In [179]:
#- Array C: 5 random integers between 1 and 100

Array_C = np.random.random_integers(1, 100, size=5)

print(Array_C)

[45  2 83 26 17]

C:\Users\dell\AppData\Local\Temp\ipykernel_18976\897282915.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  Array_C = np.random.random_integers(1, 100, size=5)

In [180]:
#- Array D: 10 evenly spaced numbers between 0 and 5 using np.linspace()

Array_D = np.linspace([0], [5]) ## start and stop values 

print(Array_D)

[[0.        ]
 [0.10204082]
 [0.20408163]
 [0.30612245]
 [0.40816327]
 [0.51020408]
 [0.6122449 ]
 [0.71428571]
 [0.81632653]
 [0.91836735]
 [1.02040816]
 [1.12244898]
 [1.2244898 ]
 [1.32653061]
 [1.42857143]
 [1.53061224]
 [1.63265306]
 [1.73469388]
 [1.83673469]
 [1.93877551]
 [2.04081633]
 [2.14285714]
 [2.24489796]
 [2.34693878]
 [2.44897959]
 [2.55102041]
 [2.65306122]
 [2.75510204]
 [2.85714286]
 [2.95918367]
 [3.06122449]
 [3.16326531]
 [3.26530612]
 [3.36734694]
 [3.46938776]
 [3.57142857]
 [3.67346939]
 [3.7755102 ]
 [3.87755102]
 [3.97959184]
 [4.08163265]
 [4.18367347]
 [4.28571429]
 [4.3877551 ]
 [4.48979592]
 [4.59183673]
 [4.69387755]
 [4.79591837]
 [4.89795918]
 [5.        ]]

<!-- 3. For Array A print:
   - Shape
   - Data type
   - Size
   - Number of dimensions -->

In [181]:
print('Shape for Array_A: ',Array_A.shape)


print('\nData type for Array_A: ',Array_A.dtype)

print('\nSize of the Array_A: ',Array_A.size)


print('\nNo. of dimensions of the Array_A: ',Array_A.ndim)

Shape for Array_A:  (10,)

Data type for Array_A:  int64

Size of the Array_A:  10

No. of dimensions of the Array_A:  1

# 4. Perform operations on Array A:
#    - Reshape to 2x5
#    - Find max value and index
#    - Find min value and index

In [182]:
print('Reshape of Array_A:',Array_A.reshape(2,5))

print('\nMax value in Array_A:', Array_A.max())

print('\nMin value in Array_A:', Array_A.min())

Reshape of Array_A: [[ 2  4  6  8 10]
 [12 14 16 18 20]]

Max value in Array_A: 20

Min value in Array_A: 2

# 5. Create Array E = [[1,2,3],[4,5,6],[7,8,9]]
#    Print element at row 1 column 2.

In [183]:
Array_E =np.array([[1,2,3],[4,5,6],[7,8,9]])


print(Array_E[1,2])

6

                ASSIGNMENT 2: NumPy Array Math Wizard

<!-- 1. Import NumPy as np.
2. Create:
   arr1 = [[1,2,3],[4,5,6]]
   arr2 = [10,20,30] -->

In [184]:
arr1 =np.array([[1,2,3],[4,5,6]])

arr2 =np.array([10,20,30])

<!-- 3. Perform:
   - Addition
   - Subtraction
   - Multiplication
   - Division -->

In [185]:


print('Addition Result: ', arr1+arr2)

print('\nSubtraction Result: ', arr1-arr2)

print('\nMultiplication Result: ', arr1*arr2)

print('\nDivision Result: ', arr1/arr2)

Addition Result:  [[11 22 33]
 [14 25 36]]

Subtraction Result:  [[ -9 -18 -27]
 [ -6 -15 -24]]

Multiplication Result:  [[ 10  40  90]
 [ 40 100 180]]

Division Result:  [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]

<!-- 5. Create arr3 = [1,4,9,16,25] and apply:
   - np.sqrt()
   - np.exp()
   - np.sin() -->

In [186]:
arr3 = [1,4,9,16,25]

print('Squre root of Array 3:', np.sqrt(arr3))

print('\nExpotant of Array 3:', np.exp(arr3))

print('\nSin of Array 3:', np.sin(arr3))

Squre root of Array 3: [1. 2. 3. 4. 5.]

Expotant of Array 3: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Sin of Array 3: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

<!-- 6. Create arr4 = [[5,12,3],[8,2,7]] and demonstrate:
   - Sum of all elements
   - Max in each column
   - Min in each row -->

In [187]:
arr4 =np.array([[5,12,3],[8,2,7]])
print('sum of all elements:',arr4.sum())


max_col =np.max(arr4, axis=0)
print('\nMax in each column:', max_col)


min_col =np.min(arr4, axis=1)
print('\nMin in each row:', min_col)

sum of all elements: 37

Max in each column: [ 8 12  7]

Min in each row: [3 2]

In [188]:
# 7. Convert arr1 to float using type casting.

float_array = arr1.astype(float)

print('\nConvert arr1 to float:', float_array)

Convert arr1 to float: [[1. 2. 3.]
 [4. 5. 6.]]

           ASSIGNMENT 3: Pandas DataFrame Detective

In [189]:
import pandas as pd

# 2. Create dictionary:

# data = {
# 'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
# 'Age': [25,30,np.nan,35,28,np.nan],
# 'Score': [85,92,78,np.nan,88,95],
# 'Grade': ['A','A','B','C','B','A']
# }

In [190]:
data = {
 'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
 'Age': [25,30,np.nan,35,28, np.nan],
 'Score': [85,92,78,np.nan,88,95],
 'Grade': ['A','A','B','C','B','A']
}

In [191]:
df = pd.DataFrame(data)

display(df)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A

<!-- 
4. Perform:
   - df.head(3)
   - df.shape
   - df.columns
   - df.dtypes -->

In [192]:
df.head(3)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B

In [193]:
df.shape

(6, 4)

In [194]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')

In [195]:
df.dtypes

Name      object
Age      float64
Score    float64
Grade     object
dtype: object

In [196]:
# 5. Missing data:
#    - df.isnull()
#    - Fill Age with mean
#    - Drop rows with missing Score

<!-- 5. Missing data:
   - df.isnull()
   - Fill Age with mean
   - Drop rows with missing Score -->

In [197]:
df.isnull().sum()

Name     0
Age      2
Score    1
Grade    0
dtype: int64

In [198]:
df['Age'].mean()

np.float64(29.5)

In [199]:
df['Age']=df['Age'].fillna(df['Age'].mean())

print(df['Age'])

0    25.0
1    30.0
2    29.5
3    35.0
4    28.0
5    29.5
Name: Age, dtype: float64

In [200]:
df['Score']

0    85.0
1    92.0
2    78.0
3     NaN
4    88.0
5    95.0
Name: Score, dtype: float64

In [201]:
df = df.dropna(subset=['Score'])

df['Score'].isnull().sum()

np.int64(0)

6. Selection:
   - Select Name and Score
   - Select rows where Score > 85
   - Set Name as index

In [202]:
df.loc[df['Score'] > 85, ['Name', 'Score']]

    Name  Score
1    Bob   92.0
4    Eve   88.0
5  Frank   95.0

In [203]:
df.set_index('Name')

          Age  Score Grade
Name
Alice    25.0   85.0     A
Bob      30.0   92.0     A
Charlie  29.5   78.0     B
Eve      28.0   88.0     B
Frank    29.5   95.0     A

In [204]:
# 7. Operations:
#    - Unique grades
#    - Grade counts
#    - Sort by Score descending

In [206]:
df['Grade'].unique()

array(['A', 'B'], dtype=object)

In [207]:
df['Grade'].value_counts()

Grade
A    3
B    2
Name: count, dtype: int64

In [209]:
df.sort_values(by='Score', ascending=False)

      Name   Age  Score Grade
5    Frank  29.5   95.0     A
1      Bob  30.0   92.0     A
4      Eve  28.0   88.0     B
0    Alice  25.0   85.0     A
2  Charlie  29.5   78.0     B